### ISSUE TITLE
Extending the Excerpt snippet with additional features.

### ISSUE THREAD

**Issue by paaljoachim** [cosmic/cosmic-tinymce-excerpt#2]
I found the following plugin:
https://wordpress.org/plugins/advanced-excerpt/

Which adds these features:

Keeps HTML markup in the excerpt (and you get to choose which tags are included)
Trims the excerpt to a given length using either character count or word count
Only the 'real' text is counted (HTML is ignored but kept)
Customizes the excerpt length and the ellipsis character that are used
Completes the last word or sentence in an excerpt (no weird cuts)
Adds a read-more link to the text
Ignores custom excerpts and use the generated one instead
Theme developers can use the_advanced_excerpt() for even more control (see the FAQ)

I made this tutorial:
http://easywebdesigntutorials.com/tinymce-excerpt-snippet/

With it I added another snippet to add a Read More to the excerpt.

I am looking into adding video so that it can show up in an excerpt.
Excerpts will likely have different sizes on the blog page. If they are split into 3-4 column boxes they might push other featured image + excerpts down. Meaning one might need to have a kind of Masonry layout of the various size boxes...

**Comment by paaljoachim** [comment]
Any thoughts as to updates?

**Comment by sunny** [comment]
Hi @paaljoachim. Thanks for the heads up!

The cosmic-tinymce-excerpt is a bit old, not really maintained and meant to be really simple so I don't think you'll see any developments on it any time soon. But the extension you mention seems really good and full of features!
